Repository mansanrod4/Acme-Toolkits, pull requests merged in 2022-03, with the labels that each got.

#80 Task-219: Cambiado critical a boolean primitivo
  src/main/java/acme/entities/Announcement.java
Labels: D02

#87 Task 222
  src/main/java/acme/entities/Patronage.java
  src/main/java/acme/entities/PatronageReport.java
  src/main/webapp/WEB-INF/resources/sample-data/patronage-report.csv
  src/main/webapp/WEB-INF/resources/sample-data/patronage.csv
Labels: rectifications

#91 Task 212: Done
  reports/D02 - E6.01 - planning_report.pdf
  reports/D02 - E6.01 - progress_report.pdf
Labels: documentation, D02
